Repository kube-arbiter/arbiter-plugins, pull requests merged in 2022-10, with the labels that each got.

#1 fix: updating project dependencies
  build/dockerfile.resource-tagger
  executor-plugins/resource-tagger/build-resource-tagger.sh
  executor-plugins/resource-tagger/go.mod
  executor-plugins/resource-tagger/go.sum
  observer-plugins/metric-server/go.mod
  observer-plugins/metric-server/go.sum
  observer-plugins/metric-server/staging/arbiter/go.mod
  observer-plugins/metric-server/staging/arbiter/pkg/proto/lib/observer/observiability.pb.go
  observer-plugins/metric-server/staging/arbiter/pkg/proto/lib/observer/observiability_grpc.pb.go
  observer-plugins/metric-server/staging/github.com/kube-arbiter/arbiter/LICENSE
  observer-plugins/metric-server/staging/github.com/kube-arbiter/arbiter/go.mod
  observer-plugins/metric-server/staging/github.com/kube-arbiter/arbiter/pkg/proto/LICENSE
  observer-plugins/metric-server/staging/github.com/kube-arbiter/arbiter/pkg/proto/lib/observer/observiability.pb.go
  observer-plugins/metric-server/staging/github.com/kube-arbiter/arbiter/pkg/proto/lib/observer/observiability_grpc.pb.go
  observer-plugins/prometheus/go.mod
  observer-plugins/prometheus/go.sum
  observer-plugins/prometheus/staging/arbiter/go.mod
  observer-plugins/prometheus/staging/arbiter/pkg/proto/lib/observer/observiability.pb.go
  observer-plugins/prometheus/staging/arbiter/pkg/proto/lib/observer/observiability_grpc.pb.go
  observer-plugins/prometheus/staging/github.com/kube-arbiter/arbiter/LICENSE
  observer-plugins/prometheus/staging/github.com/kube-arbiter/arbiter/go.mod
  observer-plugins/prometheus/staging/github.com/kube-arbiter/arbiter/pkg/proto/LICENSE
  observer-plugins/prometheus/staging/github.com/kube-arbiter/arbiter/pkg/proto/lib/observer/observiability.pb.go
  observer-plugins/prometheus/staging/github.com/kube-arbiter/arbiter/pkg/proto/lib/observer/observiability_grpc.pb.go
  scripts/build.sh
  scripts/clean.sh
Labels: size/XXL

#2 Refine code structure and fix build issue
  Makefile
  README.md
  executor-plugins/resource-tagger/Dockerfile
  executor-plugins/resource-tagger/Makefile
  observer-plugins/metric-server/Dockerfile
  observer-plugins/metric-server/Makefile
  observer-plugins/prometheus/Dockerfile
  observer-plugins/prometheus/Makefile
  scripts/clean.sh
Labels: size/M

#3 Make executor more general to support more data of OAP
  executor-plugins/resource-tagger/README.md
  executor-plugins/resource-tagger/cmd/server/server.go
  executor-plugins/resource-tagger/doc/proto/index.html
  executor-plugins/resource-tagger/go.mod
  executor-plugins/resource-tagger/go.sum
  executor-plugins/resource-tagger/internal/service/executor_wrapper.go
  executor-plugins/resource-tagger/internal/service/update_resource.go
  executor-plugins/resource-tagger/sample/resourcetagging-plugin.yaml
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/LICENSE
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/go.mod
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/pkg/proto/LICENSE
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/pkg/proto/lib/executor/execute.pb.go
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/pkg/proto/lib/executor/execute_grpc.pb.go
  observer-plugins/metric-server/server/server.go
Labels: size/XXL

#5 feat: add auto workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_request_review.yml
  .github/dependabot.yml
  .github/workflows/auto_assign_reviewers.yml
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/greetings.yml
  .github/workflows/pushimage.yml
  .github/workflows/release.yml
  .gitignore
  .golangci.yaml
  .goreleaser.yaml
  Makefile
  executor-plugins/resource-tagger/build-resource-tagger.sh
  executor-plugins/resource-tagger/cmd/server/server.go
  executor-plugins/resource-tagger/internal/service/executor_wrapper.go
  executor-plugins/resource-tagger/internal/service/update_resource.go
  hack/build-image.sh
  hack/build.sh
  hack/lib/docker.sh
  hack/lib/golang.sh
  hack/lib/init.sh
  hack/lib/util.sh
  hack/lib/version.sh
  hack/update-mod.sh
  hack/verify-all.sh
  hack/verify-copyright.sh
  hack/verify-golangci-lint.sh
  hack/verify-mod.sh
  hack/verify-shfmt.sh
  observer-plugins/metric-server/build-metric-server.sh
  observer-plugins/metric-server/main.go
  observer-plugins/metric-server/server/server.go
  observer-plugins/prometheus/build-prometheus.sh
  observer-plugins/prometheus/main.go
  observer-plugins/prometheus/prometheus/prometheus.go
  scripts/build.sh
  scripts/clean.sh
Labels: size/XXL

#20 fix: make binary failed
  hack/lib/golang.sh
  hack/lib/init.sh
Labels: size/S

#21 fix: cr format error
  observer-plugins/metric-server/example.yaml
  observer-plugins/prometheus/example.yaml
Labels: size/M

#22 Support get metric for general pql that doesn't depend pod/node resource
  observer-plugins/metric-server/main.go
  observer-plugins/prometheus/main.go
  observer-plugins/prometheus/prometheus/prometheus.go
  observer-plugins/prometheus/prometheus/server.go
Labels: size/L

#23 feat: resource tagger support support more action
  executor-plugins/resource-tagger/Dockerfile
  executor-plugins/resource-tagger/go.mod
  executor-plugins/resource-tagger/go.sum
  executor-plugins/resource-tagger/internal/service/executor_wrapper.go
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/go.mod
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/pkg/proto/LICENSE
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/pkg/proto/README.md
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/pkg/proto/executor.proto
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/pkg/proto/lib/executor/executor.pb.go
  executor-plugins/resource-tagger/staging/github.com/kube-arbiter/arbiter/pkg/proto/lib/executor/executor_grpc.pb.go
Labels: size/XXL

#25 fix: the metrics_type.go should not add copyright
  hack/boilerplate/boilerplate.py
  hack/lib/init.sh
  observer-plugins/metric-server/server/metric_types.go
Labels: size/S
